// DO NOT EDIT THIS FILE !!!
import React from 'react'

interface IQuestion {
  question: string
  options: string[]
  answer: string
}

interface IQCMInterface {
  exerciseId: string
  exerciseTitle: string
  quiz: IQuestion[]
}

const QCM: Array<IQCMInterface> = [
  {
    exerciseId: 'src/exercise/01.md',
    exerciseTitle: 'test basique avec ReactDOM',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/02.md',
    exerciseTitle: 'test avec React Testing Library',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/03.md',
    exerciseTitle: 'Test en boite noire',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/04.md',
    exerciseTitle: 'Test de formulaires',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/05.md',
    exerciseTitle: 'mocker les requêtes HTTP',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/06.md',
    exerciseTitle: 'mocker l\'API du navigateur',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/07.md',
    exerciseTitle: 'mocker un module',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/08.md',
    exerciseTitle: 'test avec Contexte',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
  {
    exerciseId: 'src/exercise/09.md',
    exerciseTitle: 'test de Hook personnalisé',
    quiz: [
      {
        question: 'Valide simplement cet exercice en cliquant sur validé',
        options: ['Validé', 'Non validé'],
        answer: '0',
      },
    ],
  },
]

//export default QCM;

const QcmComponent = () => {
  return <>{JSON.stringify(QCM, null, 2)}</>
}
export default QcmComponent
